### ISSUE TITLE
Question regarding the usage of Arc and compiler errors

### ISSUE THREAD

**Issue by terhechte** [mozilla/uniffi-rs#1048]
Hey! I'm trying to expose existing Rust code to Swift using uniffi. The Rust code uses `rusqlite` to access a SQLite database. The connection to the database is kept in a [`Connection` struct](https://docs.rs/rusqlite/0.25.3/rusqlite/struct.Connection.html#impl-Sync), which is `Send` but not `Sync`. I therefore constructed the following interface (simplified names):

``` Rust
struct Database {
  connection: Connection
}

struct Engine {
  database: Database
}

struct SwiftInterface {
  engine: Arc<RwLock<Engine>>
}

impl SwiftInterface {
  ...
  fn query(&self, query: String) -> Result<Arc<Item>> {
    ..
  }
  ...
}
```

UDL:
``` udl
interface SwiftInterface {
  [Throws=SomeError]
  Item query(string query)
}
```

All access to the database always goes through the `Arc<RwLock<Engine>>` in the `SwiftInterface`. However, compiling fails with:

```
the trait bound `Arc<SwiftInterface>: FfiConverter` is not satisfied
```

When I remove the `connection` it compiles fine (e.g.):

```
struct Database {
  // connection: Connection
}
```

On the other hand, wrapping the `connection` into an `Arc<RwLock<Connection>>` doesn't work either. Am I doing something wrong? I thought by explicitly gatekeeping all access to my Rust entities through a single `Arc<RwLock<Engine>>` the safety guarantees should be held up?

Thanks in advance for any help on this matter.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-88)
┆Issue Number: UNIFFI-88

**Comment by rfk** [comment]
> However, compiling fails with:
> 
> the trait bound `Arc<SwiftInterface>: FfiConverter` is not satisfied`

I presume this is ultimately failing because `SwiftInterface` is not `Sync + Send`, but the layers of generated code are obscuring the underlying error. I'll see if there's something we could do to improve UniFFI's error output here.

As a next step, try adding this immediately after the declaration of your `SwiftInterface` struct in Rust:

```
uniffi::deps::static_assertions::assert_impl_all!(SwiftInterface: Sync, Send);
```

This should produce a more helpful error message about exactly why Rust doesn't think your struct is `Sync`.

**Comment by rfk** [comment]
Oh, I think I see - the `RwLock` struct doesn't actually make something `Sync` if it isn't already `Sync`. The [impl of `Sync` for `RwLock<T>`](https://doc.rust-lang.org/std/sync/struct.RwLock.html#impl-Sync) requires that `T: Send + Sync`. Does it work if you try it with a `Mutex` rather than ` RwLock`?

**Comment by rfk** [comment]
> I'll see if there's something we could do to improve UniFFI's error output here.

I've filed https://github.com/mozilla/uniffi-rs/pull/1049 as an attempt to improve the error output here.

**Comment by terhechte** [comment]
Thank you, yes that fixes it 🥳. I almost feel stupid for not at least trying with a `Mutex`. ☺️
