### ISSUE TITLE
Allowing a dictionary to have fields of an interface type in UDL

### ISSUE THREAD

**Issue by chandrakananandi** [mozilla/uniffi-rs#1058]
Would it be possible to enable dictionaries to have fields that are of an interface type in UDL? For example:

interface Foo {
   constructor();
   string to_string();
};

dictionary Bar {
   Foo field1;
   Foo field2;
};

The [documentation](https://mozilla.github.io/uniffi-rs/udl/structs.html) actually does have an example of this but currently trying to implement such a UDL gives the following error: `Failed to parse UDL: Objects cannot currently appear in record fields` which is thrown [here](https://github.com/mozilla/uniffi-rs/blob/b5e7836dcc429a43a5a7a72879a985c6bddfa2f9/uniffi_bindgen/src/interface/record.rs#L135).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-92)
┆Issue Number: UNIFFI-92

**Comment by mhammond** [comment]
Thanks! This puzzled me because I thought we did have support for this, and it turns out that we di, but it is only 1/2 baked :( As you will see in #1059, the core of this does indeed work, and even appears to work for Python. It would be great if you could help push this forward for the bindings you are interested in.

**Comment by damoncro** [comment]
Same error: `Objects cannot currently appear in record fields`
