### ISSUE TITLE
Improve canonical type name patch from #1114

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#1115]
This changes the `$type_label`, instead of using the `$canonical_name`.

That should be used in the `canonical_name` method, but that's missing. 

The correct fix is to add that method (say at [L24][1]).

```rust
                 fn canonical_name(&self, _oracle: &dyn CodeOracle) -> String {
                     $canonical_name.into()
                 }
```

The fully qualified class name should be available as a type label, so as to avoid collisions with UDL declared types. e.g. if a UDL type is called `Instant` or `Duration`.

[1]: https://github.com/mozilla/uniffi-rs/pull/1114/files#diff-326998556286e54771636144110306a7bf185b8d277ff93208998226cb90116cR24

_Originally posted by @jhugman in https://github.com/mozilla/uniffi-rs/pull/1114#discussion_r756345671_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-116)
┆friendlyId: UNIFFI-116

**Comment by bendk** [comment]
My opinions on this:

 - The canonical names should be `Timestamp` and `Duration`.  I think that avoids name conflicts, since you can't create a user type named `Timestamp` in the UDL anyways
 - I don't think the the default implementation of `canonical_name()` should call `type_label()`.  In fact, it seems like we could use the same implementation for all backends.  Maybe we could just implement it as a match statement?
 - I do think we should use a FQN for `java.time.Instant` and `java.time.Duration` and also remove the import statements for them.
