### ISSUE TITLE
Use case: JSON over HTTP and CLI in other languages

### ISSUE THREAD

**Issue by Kinrany** [mozilla/uniffi-rs#1124]
Hi! I ran into this project by accident, and it looks like something I wanted for some time: a transport-agnostic IDL.

So my question is, is there any reason this couldn't be used to create a few other things based on an interface definition file?

* A JSON over HTTP server that can wrap the CLI
* A client for said server
* An alternative implementation of the CLI in another language

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-119)
┆friendlyId: UNIFFI-119

**Comment by mhammond** [comment]
Hi, and thanks for your interest.

> a transport-agnostic IDL.

I'm afraid this isn't a goal of the project - in-fact, we see IDL as more of a liability than an asset and have explored various options to deprecate it.

> So my question is, is there any reason this couldn't be used to create a few other things based on an interface definition file?

I think trying to do that would make this project lose focus from it's clear goal - to expose Rust code to foreign languages. However, [weedle](https://github.com/rustwasm/weedle/) is the IDL parser and infrastructure used by this project, so that might be a good building block for what you describe - however, IMO it's not a great fit for this specific project.

**Comment by Kinrany** [comment]
Thank you!
