### ISSUE TITLE
Panics when custom/wrapped type converters return an error.

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#1127]
Consider our `Guid` wrapped type - [it implements the trait needed by Uniffi](https://github.com/mozilla/uniffi-rs/blob/main/fixtures/ext-types/guid/src/lib.rs#L31) but `wrap` always returns `Ok` - let's assume it had an `Err` return value (eg, rejecting empty strings). All `Err` values returned by that conversion function would `panic` - uniffy will generate code similar to `<std::option::Option<FfiConverterTypeGuid> as uniffi::FfiConverter>::try_lift(val).unwrap()` when a `Guid` is taken as an arg - and that `unwrap()` panics.

The fix for that sounds fairly easy - something like: "if the function being wrapped returns a `Result<>`, just replace the `.unwrap()` with `?`, so that error propagates to the caller. This is exactly what I tried to do in #1126 - but I struck a problem with the `Err` types - the tl;dr is that the converter function returns `anyhow::Error` but the uniffi'd function returns a custom error described in the UDL and we can't convert from `anyhow::Error` to that custom error (we can go the other way, but that doesn't help us here).

So I think what we might need to do is allow an optional `Throws=` attribute on `Wrapped` types. So the UDL would look like:
```
[Wrapped, Throws=GuidError]
typedef string Guid;

[Error]
enum GuidError {
    "TooShort"
};

namespace ext_types_guid {
    [Throws=GuidError]
    Guid get_guid(optional Guid? val);
}
```

and the UniffiCustomTypeWrapper would change the wrap function from:
`fn wrap(val: Self::Wrapped) -> uniffi::Result<Self> {` (which is using `anyhow::Error`)
to
`fn wrap(val: Self::Wrapped) -> std::result::Result<Self, GuidError> {`

(which I think would be manageable when generating the ultimate `FfiConverter` crate - I think we'd just need to add another magic `.map_err(Into::into)` or similar [here](https://github.com/mozilla/uniffi-rs/blob/9e5769ec6306c9a98794417f0f232921a1b1b1d6/uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs#L36) and a few lines below)

Thought I'd throw this out there for thoughts before I charge ahead on implementing it. WDYT?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-121)
┆epic: Uniffi Places
┆friendlyId: UNIFFI-121
┆sprintEndDate: 2021-12-10

**Comment by tarikeshaq** [comment]
A few very naive thoughts, I have little knowledge of how the type wrapping works in practice, so feel free to dismiss any or all of this (and I haven't tested it so not 100% if it works either)

Will we be able to do this without changing the `FfiConverter` trait? since  [`try_lift` returns the anyhow::Result](https://github.com/mozilla/uniffi-rs/blob/main/uniffi/src/lib.rs#L187), so we end up doing the conversion anyway

Maybe have FfiConverter take an associated `Error` type? where we can keep it `anyhow::Error` for most of the implementations, but for the wrapped types,  we can have a different error

Maybe even have `UniffiCustomTypeWrapper` have an associated `Error` type, and have `FfiConverter`'s `Error` type be the same, that way, we give control to the consumer. The consumer can then make that error the same one the function throws, or another that implements `Into<ConsumerError>`, without adding any throws attributes to the `Wrapped` types

FWIW, I naively think in general having the generated code use `anyhow::Result` is a bit of a code smell :disappointed: but not sure what the best approach to go around that is

**Comment by mhammond** [comment]
> Maybe have FfiConverter take an associated `Error` type? where we can keep it `anyhow::Error` for most of the implementations, but for the wrapped types, we can have a different error

Yeah, that's an interesting idea - I wonder if we can just express the E as being Into<anyhow::Error>? I'll have a play with this, thanks.

> FWIW, I naively think in general having the generated code use `anyhow::Result` is a bit of a code smell 😞 but not sure what the best approach to go around that is

I do see the dilemma here though - a UDL file may define zero or more than one error enum, so having these traits rely on anything other than anyhow::Error has its own challenges.

**Comment by mhammond** [comment]
I pushed an update which does allow `UniffiCustomTypeWrapper` implementation to declare any Err type so long as it can Into<anyhow::Error> - which is much closer, but the arg conversion still isn't quite clear to me, but it's late - maybe it will be clear to others, or to me in the morning :)

**Comment by jhugman** [comment]
I'm not sure I understand the need for this. Why would you do anything except panic here. 

If I understand correctly, the `UniffiCustomTypeWrapper` shouldn't be receiving data it can't transform: a GUID may come from one language as a GUID, transformed and transported as a String then turned back into a GUID.

Apart from tests, how do invalid GUIDs get into the system?

**Comment by bendk** [comment]
> > Maybe have FfiConverter take an associated `Error` type? where we can keep it `anyhow::Error` for most of the implementations, but for the wrapped types, we can have a different error
> 
> Yeah, that's an interesting idea - I wonder if we can just express the E as being Intoanyhow::Error? I'll have a play with this, thanks.

I think adding an associated `Error` type to `FfiConverter` might work.
  - The ultimate goal is to serialize the error into a `RustBuffer`, which is what `call_with_result`
  - I think converting into `anyhow::Error` is going to be a dead end since we can't serialize that into `RustBuffer`. I think all we could do is panic at that point. 
  - Instead, we could use change the return type of `try_lift()` to `Result<T, Self::Error>`.  Then update the code to handle that result:
    - In the default case, when `Self::Error = anyhow::Error`, then we can call unwrap() with the result of try_lift()
    - In this case, I think we could call `map_err({{ error_type|ffi_converter }}::lower)?`

However, I would love to avoid coupling the wrapper conversion error types to the method types, which would require something like this but also changing the `call_with_result` code.  I need to think about that more though.

**Comment by tarikeshaq** [comment]
I gave the associated type a shot on https://github.com/mozilla/uniffi-rs/commit/cb09e484c5b7c353b6ed8589fa37c9b73f6fed96 the good news, it works and the test in the PR passes... the bad news:
- I had to use `std::error::Error` instead of `Into<anyhow::Error>` (maybe the latter could work, but had compilation issues 🤷) and since `anyhow::Error` doesn't `impl std::error::Error` I had to define my own concrete error
- It doesn't work well for Records, since the error would still get converted into an `anyhow::Error` (or a `UniffiConversionError` in my case) and panic'ed anyways 😞 
- Added a couple of panics, but those panics would happen anyways a few layers up the stack 🤷

**Comment by tarikeshaq** [comment]
for the point on records, 
One hand-wavy solution is to put the pressure on the consumer, (back to Mark’s idea of adding throws to types on the udl). Whenever they define and use a wrapped type. 

**If the user wants the conversion errors not to panic**, they have to define what error is thrown when that use occurs, eg:
```webidl
[Wrapped, Throws=GuidError]
typedef string Guid;

[Wrapped, Throws=URlError]
typedef string Url;

[Throws=RecordError]
dictionary Record {
   guid: Guid,
   url: Url,
}

namespace record_stuff {
    [Throws=LibraryError]
    Record get_record(optional Record? val);
}

```
(and same goes for enums with associate types)

Then force the consumer to define any `From<>` traits (which they might get for free if they use `thiserror` ). In this case, they'd have to implement ALL of:
- `From<UrlError> for RecordError`
- `From<GuidError> for RecordError`
- `From<RecordError> for LibraryError`

Some consumers might be able to set `UrlError`, `GuidError`, `RecordError` and `LibraryError` to be the exact same type, but under the hood, it would work even if they were different. 

But if the wrapped type is used everywhere, it adds lots of extra `Throws`, Of course, if a user doesn't want all the `Throws` and are happy with the panic, it'll still work 🤷 I’m just tossing ideas at this point :sweat_smile:

That all said, maybe we can fix the problem for the wrapped types directly first... then we can come back and fix how records and enums with associated data will work

**Comment by mhammond** [comment]
Thanks Tarik - that was very helpful, but I think that [anyhow::Error::downcast](https://docs.rs/anyhow/latest/anyhow/struct.Error.html#method.downcast) seems like a slightly hackier (as in, dynamically checked rather than statically checked), but overall somewhat nicer and more intuitive outcome. I've updated the PR, and have some strange `uitests` errors that I've given up on for the day, but would love (a) general thoughts on the approach (and particularly about whether it actually seems to match the expectations of the casual uniffi user) and (b) a clue about how to address those failures!
