### ISSUE TITLE
Allocate RustBuffer all at once up-front

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1152]
Investigate changing the RustBuffer code to allocate the entire buffer up-front, rather than growing it as we write to it.  This means adding code that runs before `write()` and calculates the allocation needed.  There's a few reasons for this:

 - I think it's simpler overall to allocate once.  When I was trying to track down the `LoginsKt.lower()` error, one huge source of complexity was the re-allocation strategy to grow the buffer -- Questions kept coming up like what if one of those allocations failed?  Are we sure we are copying the data correctly every time?  To me, this complexity outweighs the complexity of having to calculate the buffer size.
 - It's probably more efficient to allocate once and avoid the copies as the buffer grows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-129)
┆friendlyId: UNIFFI-129
┆sprintEndDate: 2022-02-18

**Comment by rfk** [comment]
Just sharing for context in case you weren't aware, things did operate in this allocate-up-front manner in the distant past and we changed to a growable buffer in https://github.com/mozilla/uniffi-rs/issues/251. That issue probably has useful context.

I think the main motivation there was to reduce the complexity of the codegen. Y'all have since done a lot of work on cleaning up the codegen code, so FWIW I find it very plausible that switching back to an up-front approach will work out a lot nicer than it did in the past.

**Comment by bendk** [comment]
Wow, that's extremely useful information.  I think the key issue is the one that Lina pointed out: when want to write a string, you want to be pessimistic and allocate 3 bytes per unicode character, but you could have issues because the length and capacity are probably not going to be equal.  Ironically, the change for that issue made `RustBuffer` store a separate capacity and length fields which I think solves that string issue.
