### ISSUE TITLE
Add top-level extern "C" functions for RustBuffer

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1153]
We should define top-level extern "C" functions for rust buffers.  This would be all the functions that are generated for the scaffolding code, but without the hash included:

  - `rust_buffer_alloc()`
  - `rust_buffer_free()`
  - `rust_buffer_from_bytes()`
  - `rust_buffer_reserve()`

Having these as top-level functions would allow the bindings code to access them without depending on any particular scaffolding.  This would allow us to define a `RustBuffer` wrapper in the bindings language that could be shared between all UniFFIed components.  I'm hoping to do this for the desktop-JS bindings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-130)
┆epic: Rust Components on Desktop
┆friendlyId: UNIFFI-130
┆sprintEndDate: 2022-02-18

**Comment by rfk** [comment]
> This would allow us to define a RustBuffer wrapper in the bindings language that could be shared
> between all UniFFIed components

(Hi, just continuing to drop in from time to time with historical context! 👋🏻)

One of the problems we had with this sort of thing in the past, was that we wanted to be able to support loading different Rust components from different `.so` files, for a "non-megazorded" development flow. In that sort of situation it's very important to use the individual allocation functions associated with each individual component, because each `.so` would be maintaining its own separate allocation state.

I don't *think* we have this problem any more, because we expect to always be deploying in a way that all Rust components have been compiled into the same library, and are thus sharing a single Rust allocator. Still, it's worth carefully thinking about whether there are any edge-cases where you might accidentally use the wrong allocator, or try to free memory from one allocator in a different one, or similar.

**Comment by bendk** [comment]
The historical context is amazing, thanks so much.

This change is for the second attempt at desktop-JS bindings.  For those bindings, everything is going to be in the same library -- UniFFI, all the components, the rust scaffolding, and he C++ JS code.  No dynamic loading at all.  In this situation I think a single set of `RustBuffer` functions makes sense.  But I agree that it makes a lot less sense when you're dynamically loading from `.so` libraries.

So I think what I'll try is to have these functions as `extern "C"` functions in the uniffi library, but continue to have the scaffolding code have their functions prefixed with the component name and UDL hash.
