### ISSUE TITLE
`RustCallStatus.CALL_PANIC` is represented as "success" in python helpers

### ISSUE THREAD

**Issue by ShadowJonathan** [mozilla/uniffi-rs#1158]
https://github.com/mozilla/uniffi-rs/blob/7dcbe1219eed36545effb29d8f30ca3425154212/uniffi_bindgen/src/bindings/python/templates/Helpers.py#L26-L27

Is this intentional?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-132)
┆friendlyId: UNIFFI-132

**Comment by mhammond** [comment]
I don't see why it would be intentional - best I can tell, that was introduced in bdc9551ceaca7ec0b556820e14edc8e36f2dd272 and might just be a mistake. However, we do have a [test that panics](https://github.com/mozilla/uniffi-rs/blob/7dcbe1219eed36545effb29d8f30ca3425154212/fixtures/coverall/src/lib.rs#L162) and the [Python test code](https://github.com/mozilla/uniffi-rs/blob/main/fixtures/coverall/tests/bindings/test_coverall.py#L79) seems to handle this correctly, so more digging might be needed to work out exactly what is going on here.

**Comment by bendk** [comment]
Oops, looks like a typo from me.  I think it's just the `__str__` method, which explains why the code was still working.  I'll open a PR to fix this.
