### ISSUE TITLE
What's our threading story for generated code?

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#12]
Currently, our story is something like this: the Rust components expose synchronous APIs, and do blocking filesystem I/O and network consumers. Consumers wrap them in whatever async API makes sense for their needs—Kotlin Coroutines, Swift Dispatch Queues, Gecko Background Task Queues and so on.

There are several big advantages, the biggest one being keeping our components simple:

* Pushing this to consumers gives them flexibility, since they can decide how to break up work sent to a background thread.
* Integration with libraries that do blocking I/O. Rusqlite, for example (for very good reasons!) doesn't support holding a connection or transaction open across an `await` point.
* We don't have to worry about the kinds of async deadlocks we've seen in Desktop code, where we're waiting on an operation that's waiting on us.
* The mutex protecting the `HandleMap` means we can guarantee our Rust calls will be serialized. It's easy to understand what's going on conceptually.

On the flip side:

* We end up with wrappers like a-c's `AsyncLoginsStorage`, whose reason for existence is rewrapping the logins component's API in coroutines.
* How would this work in an `async`/`await` world? Would we ever be able to migrate our components to use it? Is that a thing we want?
* It means non-blocking code has to be rewritten in a blocking wrapper to call from Rust. See Viaduct for an example.
* Blocking I/O doesn't make sense for the Desktop bindings, since chrome JS is main thread-only. So we'll need at least one async API no matter what.
* Rust has excellent support for safe concurrent programming, and compile-time guarantees for preventing data races. This offloads that responsibility to embedding languages.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1562)

**Comment by thomcc** [comment]
> Integration with libraries that do blocking I/O. Rusqlite, for example (for very good reasons!)
> ...
> Would we ever be able to migrate our components to use it? Is that a thing we want?

I think the same very good reasons (doing *any* blocking operations breaking the way tokio, async-std, etc, not to mention forcing everything we use to be fully thread-safe) would mean that we don't really want this, as attractive as it might seem

(gosh, lina is an expert lurker on rusqlite issues)

> We end up with wrappers like a-c's AsyncLoginsStorage, whose reason for existence is rewrapping the logins component's API in coroutines.

This could have been done on our side, however we weren't really sure how the situation would shake out with kotlin async, and so we left it under their control so that they could evolve it if necessary.

I believe now the a-c team has sufficient experience here that they could at least point us in the direction of async APIs that have good API surfaces (and AsyncLoginsStorage may be one of those, although I would certainly want to ask if they agreed first rather than assuming), that we could use as a model, if desired.

When that API landed this was all very new (it landed prior to kotlin async even being stable!), so that wasn't the case then.

That said, it's worth noting that *not* forcing async on our side gives our consumers more flexibility as to what thread things run on. This is valuable both for swift and kotlin, although for Kotlin it seems like running on "the IO thread" (whatever that exactly means -- there can't be just one can' there?) is possibly fine

> Rust has excellent support for safe concurrent programming, and compile-time guarantees for preventing data races. This offloads that responsibility to embedding languages.

This is not true, or maybe I'm misinterpreting you. We expose fully thread-safe APIs, and push no responsibility to use our APIs in a thread-safe manner to consumers. I think this is valuable. It would be a bad look (and a waste of a perfectly good compile-time guarantee we have) to use rust, which statically enforces thread-safety, and then throw that away at the boundary. IMO it would also make bugs much harder to track down, especially use-after-free type errors, which seem really hard to avoid with aggressive concurrent use.

**Comment by linacambridge** [comment]
Can I just say I love posting an issue and knowing you’ll bring some great feedback, as always! Thank you! 💯✨

> I think the same very good reasons (doing _any_ blocking operations breaking the way tokio, async-std, etc, not to mention forcing everything we use to be fully thread-safe) would mean that we don't really want this, as attractive as it might seem

That makes a lot of sense...I remember our initial argument against async Rust was the immaturity and complexity of the ecosystem, and while futures have stabilized since then, it doesn’t solve any of these broader problems. We have to be so mindful of the libraries we use, and the code we write on top of them, that it doesn’t feel like we’d get a payoff from doing this.

> When that API landed this was all very new (it landed prior to kotlin async even being stable!), so that wasn't the case then.

True! Now it feels like this thin wrapper, but back then, we were just figuring this stuff out. They (and we!) also iterated on that with Places, and tabs—the things that seem obvious looking back now weren’t obvious then.

> **That said, it's worth noting that _not_ forcing async on our side gives our consumers more flexibility as to what thread things run on.**

Quoting with emphasis because that’s a great point.

> I think this is valuable. It would be a bad look (and a waste of a perfectly good compile-time guarantee we have) to use rust, which statically enforces thread-safety, and then throw that away at the boundary.

I think what I was trying to say was Rust has a great async story that’s better in many ways than coroutines and dispatch queues. By offloading concurrency to those languages, we (or a-c) basically have to write that glue again, for whatever paradigm and library those languages use. In fact, though, it’s the opposite, like you pointed out—if we exposed an async API, it would be thread-_unsafe_, and we’d have to have more guardrails than we do know to prevent misuse.

**Comment by rfk** [comment]
Oh, looks like I never dove in to this thread!

> We end up with wrappers like a-c's AsyncLoginsStorage, whose reason for existence is rewrapping the logins
> component's API in coroutines.

I wonder if this could be some sort of compile-time flag when generating the bindings, where the caller could say "asyncify this class" and we add the async disptch stuff automagically. Many thorny details I'm sure, but if we're in the business of writing less boilerplate, well...

> It would be a bad look (and a waste of a perfectly good compile-time guarantee we have) to use rust, which statically
> enforces thread-safety, and then throw that away at the boundary.

big-plus-one on this point FWIW 👍 

> How would this work in an async/await world? Would we ever be able to migrate our components to use it? 
> Is that a thing we want?

I'd like to take a fresh look at what wasm-bindgen has come up with in this space, since I recall they had to grapple with that question at a pretty fundamental level. I'd like to figure out how to do it, because I have a personal side-goal here of allowing us to build plain JS+WASM versions of our components via webassembly, for use in e.g. webextensions. But from a brief experiment of trying to use wasm-bindgen on the FxA component in the past, we're going to run up against "JS crypto is always async" and "JS networking is always async" very quickly.

But I also think there's a lot of value we can delivery on other target languages before we have to grapple with that.

**Comment by rfk** [comment]
Making a note here of an interesting thing Nika mentioned in discussion just now.

The downside of us exposing nice thread-safe APIs to consumers, is that we also expose the possibility of unexpected blocking hazards.

For example, currently all accesses to methods of an `interface` are serialized by a mutex. Suppose we have an interface with an "expensive" `update` method that hits the network, and a "cheap" `check` method that only operates on local state. A reasonable consumer might arrange to call `update` on a background thread but expect to be able to call `check` from the main thread. In our current model the call to `check` can block waiting for a call to `update` to complete, janking the main thread.
