### ISSUE TITLE
how to map udl namespace to rust mod?

### ISSUE THREAD

**Issue by wuanzhuan** [mozilla/uniffi-rs#1269]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-174)
┆friendlyId: UNIFFI-174

**Comment by wuanzhuan** [comment]
i hope every rust mod can map a udl namespace

**Comment by mhammond** [comment]
A UDL file can only have a single namespace. I don't think anyone here has tried having a separate UDL file per Rust module, so I expect there will be some minor hiccups. You might also be interested in #1257, which will offer something much closer "rust native" and should remove some limitations which occur due to using UDL.
