### ISSUE TITLE
Add a `bytes` type to UDL

### ISSUE THREAD

**Issue by heinrich5991** [mozilla/uniffi-rs#1541]
Some languages, such as e.g. Python, distinguish between arrays of 8-bit integers (`List[int]` in Python) and byte buffers (`bytes` in Python).

This would IMO neatly solve #1299.

Kotlin: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte-array/
Python: https://docs.python.org/3/library/stdtypes.html#bytes

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-262)
┆Issue Number: UNIFFI-262

**Comment by linabutler** [comment]
Hi @heinrich5991, this is a nice suggestion!

A dedicated `bytes` type would also make working with byte arrays a little more ergonomic in Kotlin (in a component I was writing recently, I had to opt-in to `kotlin.ExperimentalUnsignedTypes`, then use the `toByteArray` conversion you linked to turn the `List<UByte>` into a `ByteArray`) and Swift (where we could represent them as `Data` instead of `[UInt8]`).

**Comment by badboy** [comment]
Over in Glean we also use `sequence<u8>` in at least one place and having that be `bytes` would be nice.
