### ISSUE TITLE
Support for generics

### ISSUE THREAD

**Issue by MeerKatDev** [mozilla/uniffi-rs#1755]
Will generics be supported eventually?

**Comment by badboy** [comment]
Unlikely. It's unclear how we could support those across the language boundaries.

**Comment by MeerKatDev** [comment]
are there any issues or writeups where I could see some discussion or conversation on the topic?

**Comment by badboy** [comment]
Nope, I don't think so. There might be some discussion in the chat backlog, but nothing I can point to right now.

**Comment by badboy** [comment]
What use case do you have in mind?

**Comment by MeerKatDev** [comment]
just general usage, at least for functions I would say it would be quite useful.

**Comment by badboy** [comment]
"just general usage" is very vague and not helpful.
Do you want to take in any generic type? Do you want to return generics? What about generic bounds on libstd-trait? What about user-defined traits?
A lot of that is simply impossible because we cannot determine whether a foreign object would implement a trait. So general support is not possible.
We do [support exposing traits as interfaces](https://mozilla.github.io/uniffi-rs/udl/interfaces.html?highlight=trait#exposing-traits-as-interfaces). That way the traits and trait objects stay fully on the Rust side.

**Comment by MeerKatDev** [comment]
Okay, thanks for the answers, I will think about it and get back with some more details eventually.

**Comment by skeet70** [comment]
Would making only unconstrained generics possible still be a big lift? I'm thinking of enabling container types, list types, etc. In our specific use case its

```
struct BatchResult<T> {
  successes: HashMap<String, T>,
  failures: HashMap<String, ConcreteErrorType>
}
```

For now we're going to use a macro to generate the N instances of that type we need, but AFAIK that sort of generic use could work in downstream languages and would make for more ergonomic/easier to document generated code.

**Comment by badboy** [comment]
This would still require a concrete Rust type at some point. We need to go over the FFI; how do you decide what type `T` is there?

**Comment by skeet70** [comment]
Maybe the containing type could only be instantiated in Rust, and the generic has to be a type that can already go across the FFI binding (either a primitive or a type already known to uniffi)? Then it'd go across as a painter to a type that's already known.

I'm not sure, only wondering, because even that would be useful. If I get some time I can mess around with augmenting generated code to get a more concrete idea.
