### ISSUE TITLE
Docstrings for proc macros compile error when > 255 characters

### ISSUE THREAD

**Issue by dani-garcia** [mozilla/uniffi-rs#1874]
I saw the the proc macro support for docstrings was merged recently so I decided to test it in some projects, and I noticed that any  docstring longer than 255 characters will fail to compile with the following error:

```
error[E0080]: evaluation of constant value failed
   --> /Users/dani/Desktop/uniffi-rs/uniffi_core/src/metadata.rs:178:9
    |
178 |         assert!(string.len() < 256);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: string.len() < 256'
    |
note: inside `MetadataBuffer::concat_str`
```

This is the code used to test this:
```rust
/// This is a very long multi line test docstring that exceeds 255 characters.
/// This is a very long multi line test docstring that exceeds 255 characters.
/// This is a very long multi line test docstring that exceeds 255 characters.
/// This is a very long multi line test docstring that exceeds 255 characters.
#[uniffi::export]
pub fn test2() {
}
```

This seems to be caused by the way `MetadataBuffer` stores strings, by encoding their length as a `u8`. This limits their max length to 255, which is easily exceeded if the docstring contains some complex explanation or code example.

My first thought would be to update `MetadataBuffer::concat_str` to encode the length as a `u16` instead, and change `MetadataReader` to do the same, but I'm not sure if that will have some adverse effects somewhere else.

**Comment by mhammond** [comment]
Ouch, thanks! IIUC the only adverse impact would be to increase the size of the metadata stored in the binaries. I'm not sure that matters much because I expect we will update our docs to recommend stripping all symbols after generating the bindings but before shipping. OTOH, I think we could also invent a new, say, "long_string()" concept, used just for this, and leave all the other strings alone.
