### ISSUE TITLE
Allow UniFFI exported types (e.g. `Object`) from EXTERNAL crates to be used in a crate's e.g. `Record`

### ISSUE THREAD

**Issue by Sajjon** [mozilla/uniffi-rs#1965]
@bendk [asked my in this Matrix thread](https://matrix.to/#/!tsNDDGHvNGVNmvOOzi:mozilla.org/$w1jdiFwzlq5GKoK2Uv3gUzoodvZfG9Ph_YEUT63fEjY?via=mozilla.org&via=matrix.org&via=element.io) to open a GH issue for this

# Context
I'm writing a lib which must fully control Serde and UniFFI exporting of all types, this involves a lot of newtype pattern and usages of `uniffi::custom_newtype!`, so that I can implement custom Serde for it.

However, one type is quite complex and I would like to write as thin a wrapper as possible around an external type, a (Big)Decimal type. [Radix Engine Toolkit's (short: RET) UniFFI crate vendors a Decimal type, lets call it `RETDecimal`](https://github.com/radixdlt/radix-engine-toolkit/blob/main/crates/radix-engine-toolkit-uniffi/src/common/decimal.rs#L30), which is UniFFI exported as `Object`, it itself actually just wraps the Decimal type from another crate (another repo): [Radix Scrypto Decimal lets call it `NativeDecimal`](https://github.com/radixdlt/radixdlt-scrypto/blob/main/radix-engine-common/src/math/decimal.rs#L42).

`NativeDecimal` in Scrypto repo knows nothing about UniFFI.

My lib lives in another repo than `RETDecimal` and another repo than `NativeDecimal` (perhaps only crate hierarchy is relevant, not repo...).

What I would like to have is something like:

```rust
#[derive(uniffi::Object)]
pub struct Decimal(AnyOfTheOtherTwoDecimalTypes);

#[uniffi::export]
impl Decimal {
    pub fn add(&self, other: Self) -> Self { ... }
    pub const fn zero() -> Self { ... }
   // ... + 100 other methods and functions
}
```

Where by `AnyOfTheOtherTwoDecimalTypes` I mean I'm happy with using already UniFFI exported `RETDecimal` from `RET` crate, or the wrapped type it uses, `NativeDecimal` from the `Scrypto` crate (which does not know anything about UniFFI).

or alternatively `Record:

```rust
#[derive(uniffi::Record)]
pub struct Decimal {
    inner: AnyOfTheOtherTwoDecimalTypes,
}
```

And the same API - as in exposed functions and methods. 

It is **important** that the `Decimal` type must not be a typealias to a primitive in the Swift (or Kotlin) land, it must be its own type. I do not care about the fields of it, so it can be an `uniffi::Object` - however in the Rust land using `Object` requires usage of `Arc`, which breaks derive of `Hash` and `Eq` of an owning holder of the type... why I prefer `uniffi::Record`.

Yes I know, `Record`s cannot have methods, it is OK, I would create global freestanding functions and in the Swift land I would create extensions:

```
extension Decimal { 
    func add(other: Self) -> Self { 
        // calling UniFFI exported global freestanding method since `Decimal` is a `Record` which does not support methods
        addDecimal(self, other)
    }
}
```

# Failed attempts
As seen in the [Matrix thread](https://matrix.to/#/!tsNDDGHvNGVNmvOOzi:mozilla.org/$w1jdiFwzlq5GKoK2Uv3gUzoodvZfG9Ph_YEUT63fEjY?via=mozilla.org&via=matrix.org&via=element.io), I've tried `uniffi::custom_newtype!(Decimal, RETDecimal);` which did not work. I also tried:

```rust
impl crate::UniffiCustomTypeConverter for Decimal {
    type Builtin = RETDecimal;
    ...
}
```

Did not work.

And I've tried:

```rust
unsafe impl<UT> Lower<UT> for Decimal {
 ...
}
```

Did not work.

Then as per suggestions I've tried:

```rust
[ExternalInterface="radix_engine_toolkit_uniffi"]
typedef extern Decimal;
```

But did not get that to work either.

Hopefully there is a combination of any of the three + `[Extern]` in UDL which will work that I have not yet found.

**Comment by Sajjon** [comment]
Thx! I will give it a go

**Comment by CyonAlexRDX** [comment]
(This is @Sajjon under work Github username)
@bendk is it possible to "bulk re-export" a crate? What do I mean by that? The `radix_engine_toolkit_uniffi` (short: RET) crate is quite big, the [resulting header file is 2000 lines](https://github.com/radixdlt/swift-engine-toolkit/blob/main/Sources/RadixEngineToolkit/RadixEngineToolkit.xcframework/ios-arm64/RadixEngineToolkit.framework/Headers/radix_engine_toolkit_uniffiFFI.h). Above it sounds like I have to define **each** RET type in the UDL of my crate `Sargon` (repo: RadixWalletKit)? Also hmm how does it work with *functions* inside of RET? Is it possible to re-export `RET`'s uniffi exported functions with my crate `Sargon`?

Instead of having to put an entry for each RET type (and function?) in Sargon's UDL, is it somehow possible to in Sargon say "I wanna RE-EXPORT the whole of RET", so that all consumers of Sargon's UniFFI also gets RETs symbols (types and functions)?

Maybe my question does not make sense, sorry, I have a bad understanding of how a crate with UniFFI support can re-export/re-vendor another crate also with UniFFI support :).

**Comment by bendk** [comment]
With the approach above, you still need to flag types used across crates in the UDL file with `[External]`, but that's usually much fewer types.

**Comment by mhammond** [comment]
There's some interest around external/remote/custom types recently, so it would be great to see this looked at again. I'm struggling to work out what's being asked for exactly here though - maybe a minimal code-only sketch of the problem? I'm going to close this now but would love to find out what the ask here is for exactly in another issue.
