### ISSUE TITLE
Support returning objects from functions and methods

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#197]
As part of #37 and complementing #40. Putting this here so it doesn't get lost.

We should be able to return objects from functions and methods: 

e.g. 

```kotlin
val pool = new ThingPool()
val thing = pool.getOrCreate(id = "abc")

// later on 
val sameThing = pool.getOrCreate(id = "abc")

// The objects are equal.
assert(thing == sameThing)

// The objects are the same.
// it might be ok if this isn't true, but we need to discover the assumptions and document them.
assert(thing === sameThing)
```

The `===` case is the hard bit! We could maintain a `handle_map` on the platform side, but then we have some book keeping to do around destruction, including if the object is destructed on the Rust side. If the objects **must** be the same, then we should do it in a separate issue.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1596)

**Comment by rfk** [comment]
Ref https://github.com/mozilla/uniffi-rs/pull/366#discussion_r557002595 for a concrete use-case for this.

**Comment by rfk** [comment]
Since this was on my radar, a bit of a brain-dump of another possible source of complexity here...

When returning an object from a Rust function, how do we know whether this was an object that was already in the handlemap, or whether it needs to be added to the handlemap? If it's an existing instance, how do we discover its existing handle in order to return that value across the FFI? I feel like we may have to expose some of the internal details of how the handlemap works so that the hand-written Rust code for the component can cooperate with the generated Rust scaffolding in order to make this work.

**Comment by rfk** [comment]
This is now possible as of v0.12.0.
