### ISSUE TITLE
External callback interfaces/traits feature request

### ISSUE THREAD

**Issue by Voronar** [mozilla/uniffi-rs#2007]
External callback interfaces [not supported at the moment](https://github.com/mozilla/uniffi-rs/blob/0a5e2eb5760b4ce5549021ec91de546716de8db1/uniffi_meta/src/group.rs#L214).
Please add the support or make foreign traits usable externally.

**Comment by mhammond** [comment]
Callback interfaces are less likely to get love moving forward. I was going to suggest you use an external "trait" instead, but noticed that too appears to not be supported :( I'll rename this to handle both cases because the work for both will be very similar.

**Comment by cowlicks** [comment]
@mhammond can you say a little more about this? I'd have a few functions that accept simple callbacks in my api. I'm trying to figure out the best option for supporting these. The functions are mostly for convenience.

I'm wondering why was the callback interface deprecated? They are mentioned as "(soft) deprecated" in the docs (but not in the pro macro docs). Soft deprecated implies that I may be able to use and maybe wait for whatever future thing might be in the works to replace them. Are there plans to support callbacks in the future?

Why were external traits deprecated? I don't see this mentioned in the docs.

Sorry for all the questions. But I'm hoping with more info I may be able to help with a future solution.

**Comment by mhammond** [comment]
callbacks are kinda soft-deprecated because "foreign traits" offer all the same capabilities with a more consistent interface. In particular, callback interfaces are passed to rust as a `Box<dyn Trait>` which makes sharing them complicated, whereas traits are passed around as `Arc<dyn Trait>`. I'm not aware of anything callbacks can do that traits can not, but this difference means traits are capable of things callbacks are not.

external traits were never deprecated - they just were never supported - just like they were not for callbacks. Of those 2, I suspect external traits will get support first as it covers more use-cases (ie, both traits that are not designed to be implemented externally and those that are).

**Comment by cowlicks** [comment]
@mhammond Thank you! I understand now. I was confusing "foreign" and "external" traits above, when I read your comment that external traits are not supported.

**Comment by BatmanAoD** [comment]
The ["callback interfaces" documentation](https://mozilla.github.io/uniffi-rs/0.27/udl/callback_interfaces.html) should definitely link to the "foreign traits" guide. Under "defining a callback," there's a comment saying `// as described in the foreign traits docs... `, but I had no idea until I found this issue that that meant Foreign Traits were _not_ deprecated and should be used instead of callback interfaces.

**Comment by mhammond** [comment]
I think everything we intend to do here is done, thanks!
