### ISSUE TITLE
Feature Request: Add SwiftLint disable in generated Swift file

### ISSUE THREAD

**Issue by martinmose** [mozilla/uniffi-rs#2020]
Hello,

I've noticed a small enhancement that could benefit developers using SwiftLint alongside the files generated by Uniffi. 
It would be helpful to include `// swiftlint:disable all` at the beginning of the generated Swift file and `// swiftlint:enable all` at the end. 
This practice is already adopted by other popular generation tools, such as SwiftGen, and would streamline the workflow for some iOS developers 🍎 by eliminating the need to manually ignore the generated Swift file in SwiftLint.

I appreciate your consideration 🤞

**Comment by badboy** [comment]
Would you mind sending a PR for that?
Should be as easy as doing it in https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/wrapper.swift

(Personally I just have the folder containing the generated code in the `excluded` list, but otherwise I would have noticed that earlier too)

**Comment by martinmose** [comment]
Yes of course! I should have done that in the first place. Thanks.

**Comment by badboy** [comment]
Closed by #2038
