### ISSUE TITLE
Trait’s associated types support

### ISSUE THREAD

**Issue by zllak** [mozilla/uniffi-rs#2026]
Is there a plan to implement support for associated types in traits? Maybe not generic associated types just yet tho.
As far as I have looked there is equivalent in Swift and Kotlin.
It will be interesting to create support for Stream-like traits.

If you think this can be a nice addition, I’ll be happy to work on this. But I am a uniffi user but not really familiar with the codebase so I’ll happily take some advice on implementing it.

Thanks

**Comment by mhammond** [comment]
I did have a play with this a year or 2 ago, and while it nearly worked it ended up with a few problems - trying to use associated types in the bindings is probably a non-starter because it can't be made to work with all bindings, and resolving the types before the bindings saw them didn't really offer much value.

So I'd suggest that before working on this you flesh out exactly what semantics you are proposing and how those semantics map to each binding, including the external bindings of c# and golang.

**Comment by zllak** [comment]
I think in Swift and Kotlin it’s pretty straightforward, I have not looked for Python and Ruby. But you also want to support the 3rd party languages, which are not officially supported by uniffi ? This seems a bit out of scope no ? Anyway I’ll try to come up with a prototype for at least the officially supported languages.

**Comment by mhammond** [comment]
> But you also want to support the 3rd party languages, which are not officially supported by uniffi ?

I don't think that's really an accurate characterization - these languages aren't in our repo because we explicitly requested they be maintained externally because we don't have the expertise to manage them and we are happy for them to be a little behind this repo in terms of new features - but that doesn't mean we consider them any less valuable or important to uniffi's success.

**Comment by cowlicks** [comment]
I'm also interested in support for stream-like traits. Specifically in [python](https://peps.python.org/pep-0525/) and [javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols) which both have stream-like things. For a workaround without associated types I was thinking perhaps using something like a attribute macro to mark a trait or impl block to use for creating the downstream stream code.

**Comment by zllak** [comment]
I have done some digging and it seems pretty straightforward for Kotlin, Go, and Swift, I unfortunately don't have time to investigate for other languages.
Not sure what you want to do with this issue but i'm afraid it will be too time consuming for me, knowing that we can work around that for the use cases I have.
I'll close it for now
