### ISSUE TITLE
Question: Convention for using UniFFI with SwiftUI (Update a SwiftUI view when a UniFFI interface object changes).

### ISSUE THREAD

**Issue by GraniteLake** [mozilla/uniffi-rs#2145]
SwiftUI uses property wrappers such as @StateObject and @ObservedObject on an ObservableObject (a type of object with a publisher that emits before the object has changed) parameter of a SwiftUI view to update the view whenever the parameter's published properties change (see https://developer.apple.com/documentation/Combine/ObservableObject).

UniFFi issue #2097 discussed that UniFFi does not currently support swift property wrappers but the creator of the issue indicated that there is a convention for using UniFFI with SwiftUI and I was wondering which convention is used to have a SwiftUI view update when a UniFFI interface object changes?

**Comment by cadnza** [comment]
Answered [here](https://github.com/mozilla/uniffi-rs/issues/2097#issuecomment-2150529901), to be taken with a huge grain of salt

**Comment by mhammond** [comment]
I think @Sajjon has some interest/knowledge here?

**Comment by Sajjon** [comment]
Hey! There are several dimension to using UniFFI and SwiftUI; let me start by trying to reduce the scope a bit...

What is your minimum deployment target? If you can target iOS 17, you can simply write one wrapping model per screen, lets call it ViewModel, which is a class and annotate it [with `@Observable` macro ](https://developer.apple.com/documentation/observation/observable()). Which does not require the store property to have been marked with anything IIRC. So you can use UniFFI exported classes (or enums / srructs) as stored properties in this ViewModel.

This "solves" your issue completely without any changes needed to SwiftUI.

If you need to target lower than iOS 17, you can employ the same technique with [PointFrees Perception framework](https://github.com/pointfreeco/swift-perception).

It might be interesting to explore possibilities to in Rust with UniFFI mark a `uniffi::Object` to be marking the Swift class with `@Observable`, but it being iOS 17+ we would need to wrap it with conditional compilation. We would also need to mark the generated swift file with `#canImport(Observation)` because it is not available for Linux.... so there are several missing pieces and challenges in doing so. Foremost we don't have any UDL spelling nor proc-macro for binding language specific settings for certain types. It would be very nice to have though! E.g. being able to express mutable/immutable stored properies on **certain** Swift types, and not catch em all, like we have today. Maybe @mhammond or @bendk can share some thoughts about that specifically...

If you are not using/required to use "vanilla SwiftUI" - whatever that means, since there is no clear standard; why I'm a huge fan of opinionated [TCA](https://github.com/pointfreeco/swift-composable-architecture) by PointFree too - finally a standard! But I'm digressing... I was gonna say that I've recently managed to [POC with TCA and SharedState with UniFFI.](https://github.com/radixdlt/sargon/pull/131). Big PR... TL;DR; my app is completely driven by UniFFI, an object (swift class) for which I have a singleton, lets call it `App`. Hosts (iOS TCA+SwiftUI apps / Android Kotlin app) implement "Drivers" which are UniFFI traits which App uses to make use of ""peripherals"" on the host: networking (URLSession), file IO, unsafe storage (UserDefaults), secure storage (keychain), and "EventBus" ([AsyncPassthroughSubject](https://github.com/sideeffect-io/AsyncExtensions/blob/main/Sources/AsyncSubjects/AsyncPassthroughSubject.swift)) with which `App` can emit "notifications" Rust side, with which I've implemented a custom PersistenceKey being the building block for `@SharedReader` in TCAs state - which is `@ObservableState` - TCAs value semantics analogue counterpart to `@Observable`.

**Comment by mhammond** [comment]
> Foremost we don't have any UDL spelling nor proc-macro for binding language specific settings for certain types. It would be very nice to have though! E.g. being able to express mutable/immutable stored properies on **certain** Swift types, and not catch em all, like we have today. Maybe @mhammond or @bendk can share some thoughts about that specifically...

We'd probably prefer to keep things which are language-specific like that in `uniffi.toml` for as long as we can - eg, you would list those types there and it would influence the binding generator. Expressing this inside proc-macros would be both tricky (because we don't really have a way to carry arbitrary metadata from proc-macros all the way to the scaffolding generation) and it seems like it would become unwieldy if all languages ended up with their own set of custom things. That said though, we do try and be pragmatic.
