### ISSUE TITLE
uniffi-bindgen should snake-case and lower-case Rust-side methods

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#225]
Take the following interface:

```
interface FirefoxAccount {
  string getPairingAuthorityURL();
}
```

`uniffi-bindgen` will generate the following:
```
let _retval = FirefoxAccount::getPairingAuthorityURL(obj);
```

instead it should call `FirefoxAccount::get_pairing_authority_url` (Rust convention).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1643)

**Comment by rfk** [comment]
There's some historical discussion of this over in https://github.com/mozilla/uniffi-rs/pull/2 for context.

I am lightly of the opinion that since you're writing the IDL and the Rust code at the same time, it should be up to you to make sure the names match, ref this comment https://github.com/mozilla/uniffi-rs/pull/2#discussion_r444012978. But I will happily defer to the lived experience of actually using this tool in practice, and if writing the IDL in rust naming convention syntax feels unnatural, I don't object to doing a bit of case-conversion.

**Comment by eoger** [comment]
Actually I didn't realize the Kotlin bindings have the correct case, so I'm fine with leaving .idl files as-is.
