### ISSUE TITLE
Add map type support

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#226]
Just like sequences, but for associative arrays.

EDIT: renamed the issue to avoid confusion with our current dictionaries support.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1644)

**Comment by eoger** [comment]
For what it's worth I don't see any support for this in the WebIDL spec

**Comment by rfk** [comment]
> For what it's worth I don't see any support for this in the WebIDL spec

Aye. I think we are starting to bump up against the limits of WebIDL (which was always going to happen at *some* point, but TBH I'm a little surprised it's happened so quickly). I'm not sure there's a good way to parse something like `Map<Key, Value>` using weedle.

**Comment by rfk** [comment]
Oh! It does have this `record` type for representing ordered maps:

* https://heycam.github.io/webidl/#idl-record

Which...I think it would be extremely confusing because uniffi turns WebIDL `dictionary` types into something called a `Record`, and we'd be turning the WebIDL `record` type into what many languages refer to as a `dictionary` 🤦

**Comment by linacambridge** [comment]
There's also `maplike` which corresponds to a JS `Map`.

**Comment by eoger** [comment]
That's pretty cool, it looks harder to implement though since it's an interface?
