### ISSUE TITLE
Add a uniffi-bindgen binary to one of the crates.

### ISSUE THREAD

**Issue by afranchuk** [mozilla/uniffi-rs#2278]
This would be a convenient thing for users to `cargo install`. I suppose it should be in `uniffi` since that's where `uniffi/cli` code exists. 

This should come with a warning that the version of `uniffi-bindgen` used must match the version being used in your crate (and recommend using `cargo install --version <version>` to guarantee this). This also allows nightly users to easily install the appropriate `uniffi-bindgen` binary due to [this unstable functionality](https://doc.rust-lang.org/cargo/reference/unstable.html#artifact-dependencies).

**Comment by badboy** [comment]
We explicitly [removed the binary in v0.23.0](https://github.com/mozilla/uniffi-rs/blob/881d57cf9c7a23a90095eb4158ab9675f5238f8a/CHANGELOG.md#%EF%B8%8F-breaking-changes-%EF%B8%8F-2), because it frequently lead to version imcompatibilities when people never updated the binary again.

The recommendation is to have your own binary in your project, re-using the same dependency version.
