### ISSUE TITLE
Using async traint crashes at "Foreign pointer not set"

### ISSUE THREAD

**Issue by crazytonyli** [mozilla/uniffi-rs#2343]
I ran into a crash when having a crate using an async trait defined in another crate. Here is the crash site.

https://github.com/mozilla/uniffi-rs/blob/2c003b16d1e70e1914b5d8ceb517eef3676cd187/uniffi_core/src/ffi/foreigncallbacks.rs#L31-L33

To reproduce this crash:
1. Get the project from https://github.com/crazytonyli/uniffi-foreign-async-crash
2. Run `./build.sh && swift test --package-path swift`. You can see the full backtrace from Xcode, too.

I'm using Xcode 16.1 on macOS 15.

**Comment by mhammond** [comment]
Thanks for the report. One of us will try and repro this, but if you'd like to help things along, the most impactful thing you could do would be to submit a patch which demonstrates it in our fixtures - this is the first thing anyone would need to do regardless so that any fix has suitable tests, and having this done beforehand would make it that much more tractable for one of us to look into the actual problem.

**Comment by crazytonyli** [comment]
I can have a look at that if I find some time. Meanwhile, to whoever is looking at this issue, please feel free to use the code in the project if needed.

**Comment by bendk** [comment]
I believe https://github.com/mozilla/uniffi-rs/pull/2367 fixes this one
