### ISSUE TITLE
downcasting or type casting

### ISSUE THREAD

**Issue by Alphapage** [mozilla/uniffi-rs#2373]
Hello,

I am trying to downcast a class which inherits another class from Swift.
rust part:
```
#[derive(uniffi::Object)]
struct Casting {
    // commands: RwLock<Vec<Arc<dyn ImplCastingTrait>>>,
    cast: Arc<dyn ImplCastingTrait>,
}

#[uniffi::export(with_foreign)]
#[async_trait::async_trait]
pub trait ImplCastingTrait: Send + Sync {}

#[uniffi::export]
impl Casting {
    #[uniffi::constructor]
    pub fn new(cast: Arc<dyn ImplCastingTrait>) -> Self {
        Self {
            cast, // commands: RwLock::new(Vec::new()),
        }
    }

    pub fn try_cast(&self) -> Arc<dyn ImplCastingTrait> {
        self.cast.clone()
    }
}
```
swift code:
```
class CastObj: UIView, ImplCastingTrait {}

let c = Casting(cast: CastObj())
        let v = c.tryCast() as! UIView // error here, but I can downcast to ImplCastingTrait
```

For now, I must use `any ImplCastingTrait` in swift, but it would be great if I could switch this swift code or any foreign language to rust.

Thank you in advance for your help.

**Comment by linabutler** [comment]
Hi again, @Alphapage!

> it would be great if I could switch this swift code or any foreign language to rust.

This isn't possible to support, because `c.tryCast()` returns a UniFFI-generated _wrapper_ around `CastObj()`. The generated wrapper conforms to `ImplCastingTrait`—which is why `as any ImplCastingTrait` works; it's a no-op, not a downcast—but it has a different memory layout than `CastObj`, which is why the `as! UIView` cast fails.
