### ISSUE TITLE
Replace `calculateWriteSize` with a growable buffer

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#251]
Each of our foreign-language bindings generators currently implements a `calculateWriteSize` method of some sort, which is used when serializing complex datatypes to send over the FFI like so:

1. Call `calculateWriteSize(v)` to determine the precise number bytes into which `v` will serialize.
2. Allocate a `RustBuffer` of exactly that size.
3. Serialize `v` into the allocated buffer.

In retrospect, I think this was a premature optimization, and it's not serving us well in practice. Two downsides come to mind:

* It adds nontrivial cognitive overhead to working on the bindings generator, multiplied by the number of bindings backends.
* It adds overhead for serializing strings in languages where utf8 is not the native encoding, since you end up converting the string to utf8 twice - once to find out how many bytes it occupies, then a second time to actually serialize it.

Notably, the rust scaffolding does *not* pre-calculate sizes in this way when returning complex datatypes; it just uses a `Vec` and allows the `Vec` to automagically grow as required.

I think we should do the same thing on the foreign-language side, as follows:

* Add an FFI function `ffi_bytebuffer_reserve(buf, n)` which calls through to [Vec::reserve](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve) in the rust code.
* In each of the foreign-language bindings, at the point where we check that we're not writing past the end of the buffer, have it call `ffi_bytebuffer_reserve` rather than throwing an error.
* Delete all the `calcaulteWriteSize` stuff from the foreign-language bindings.

Rust's `std::vec::Vec` does not guarantee any particular growth strategy when calling `reserve` multiple times, but it *does* claim that calling `push()` multiple times will have `O(1)` amortized cost per element That's good enough a guarantee for our purposes here, and we should expect that serializing any particular value in this way will involve a sub-linear number of calls to `ffi_bytebuffer_reserve`. (In practice right now `Vec::reserve` always at least doubles the size of the underlying buffer, which is what we'd do if we had to manage a growable buffer for ourselves).

Any objections?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1678)

**Comment by linacambridge** [comment]
Hah, perfect timing!

This is a wonderful idea! I was just about to post an issue related to `calculateWriteSize`, but getting rid of it entirely and letting the bindings grow the buffer as needed would solve that and a bunch of other problems.

The specific snag I ran into was about encoding strings. Gecko has two string classes: `nsCString` for "narrow" strings of an unspecified encoding (can be 7-bit ASCII, Latin-1, UTF-8, etc.), and `nsString` for "wide" strings, which are always UTF-16. WebIDL and JS _really_ like UTF-16 strings...which is great, except Rust is expecting UTF-8, so we need to convert them. But there's no API in Gecko for determining the UTF-8 encoded size of a UTF-16 string—we have to convert the string first, and then get its length. That leaves us in an unfortunate place because we need to know the encoded size to allocate the buffer!

So we either allocate and convert the string twice—once just to get its length,  and a second time to write it into the allocated Rust buffer—or we pessimistically overallocate in `calculateWriteSize`, and write the actual number of bytes later. I went with the second approach, but that has two problems.

1. It's wasteful! We can optimize for ASCII strings, but, as soon as we have a non-ASCII character in a JS string, we'll allocate a buffer that's three times the size of that string. This is the minimum size of the buffer we need to hold a pathological worst case where literally every character is multiple bytes (like a string with all emojis! 👀 🚀😍🤪)
2. It won't actually work :joy: We'll end up leaving junk in the buffer, because we might have asked for a Rust buffer that's 30 bytes, but only written 10, and Rust will panic. And we can't truncate the Rust buffer's `len`; that will corrupt Rust's allocator when [the destructor frees the byte buffer](https://github.com/mozilla/application-services/blob/d0c67c9dc21c3e2571f828113c22a7b123854597/components/support/ffi/src/lib.rs#L538) (violating the [fourth invariant documented here](https://doc.rust-lang.org/std/vec/struct.Vec.html#safety) and sending us on an all-expenses-paid trip to Undefined Behavior-land).

If we got rid of the precalculation, and grew the byte buffer as needed, we could avoid all these shenanigans. It would also mean we could change the Swift bindings to write directly into the `RustBuffer`, instead of copying everything into `Data`, and copying it all again to make a `RustBuffer`.

**Comment by linacambridge** [comment]
> If we want a growable version of this, we probably can't use `ffi_support::ByteBuffer` as-is and will instead have to make our own version that supports an explicit `capacity` field.

Something that just occurred to me is, could we encode the length and capacity in the allocation itself, instead of passing around a `RustBuffer` struct with the length and capacity? I think [ThinVec](https://docs.rs/thin-vec/0.2.1/thin_vec/struct.ThinVec.html) does something like this under the hood. Then we could theoretically reconstruct (and free) the buffer with just a pointer to its data, and without knowing its length and capacity. But that means we couldn't use `Vec` to back the buffer, which might be more disruptive than it's worth.

**Comment by rfk** [comment]
> that means we couldn't use Vec to back the buffer,

I am highly motivated to continue using the builtin `Vec` to back the buffer, FWIW.

**Comment by rfk** [comment]
I should mention, I started messing around with this a little, and got as far as to make my own version of `RustBuffer` with the extra capacity field. I got a bit stuck on trying to implement the "write into this buffer and grow it on demand" logic on the Kotlin side, planning to revisit it in the next couple of days.

(By the way, one side-benefit of not using the default bytebuffer stuff from ffi-support, was that I could make all the builtin support functions take an `out err` parameter and simplify away the `has_out_err` logic when generating the FFI bindings. I think this will fit nicely with your recent work on panic-safety @linacambridge).
