### ISSUE TITLE
Cannot send dictionaries with all optional fields to JS

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#331]
From https://jira.mozilla.com/browse/NIBSSD-87:

> 0:05.97 WebIDL.WebIDLError: error: Dictionary argument without any required fields or union argument containing such dictionary not followed by a required argument must be optional, /Users/dmose/r/hg-mc/toolkit/components/nimbus/Nimbus.webidl line 43:35
> 0:05.97 AvailableRandomizationUnits available_randomization_units

The short term fix was to add a required dummy field, but it doesn't sound like a great solution.
Maybe when we detect a dictionary with all-optional fields, we could declare the dictionary as optional in the WebIDL and transform that later to a non-optional type in the Rust translation layer (using `Default::default()`)?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-31)
┆Issue Number: UNIFFI-31

**Comment by rfk** [comment]
> that later to a non-optional type in the Rust translation layer (using Default::default())?

If this issue is specific to the JS bindings, I think I'd prefer the workarounds to also be specific to the JS bindings, which IIUC would mean converting from "missing dictionary" to "dictionary will all fields missing" in the C++ layer, before it hits the Rust code.

On the other hand, I can see a developer-convenience argument that we should uniformly `null` anywhere we accept a dictionary whose fields are all optional, in which case it would make sense to do it in the Rust layer.

**Comment by rfk** [comment]
Closing old Gecko issues and consolidating them under https://github.com/mozilla/uniffi-rs/issues/991
