### ISSUE TITLE
failed to generate C header of rust scafolding code

### ISSUE THREAD

**Issue by chenzww** [mozilla/uniffi-rs#364]
I follow the official `The uniffi user guide`.
Execute "cargo build" to generate scaffolding code for math.udl.
Then execute "cbindgen --lang c --crate <crate_name> --output <c_header_name>.h".
There is not any interface code related to rust scaffolding code in the generated C header file.

Then, I tried to remove include! macro and  paste the Rust scaffolding code into the `src/lib.rs` file. 
The following warning message is output on the command line:
```
WARN: Can't find RustBuffer. This usually means that this type was incompatible or not found.
WARN: Can't find ExternError. This usually means that this type was incompatible or not found.
WARN: Can't find RustBuffer. This usually means that this type was incompatible or not found.
WARN: Can't find ForeignBytes. This usually means that this type was incompatible or not found.
WARN: Can't find ExternError. This usually means that this type was incompatible or not found.
WARN: Can't find RustBuffer. This usually means that this type was incompatible or not found.
WARN: Can't find ExternError. This usually means that this type was incompatible or not found.
WARN: Can't find RustBuffer. This usually means that this type was incompatible or not found.
WARN: Can't find RustBuffer. This usually means that this type was incompatible or not found.
WARN: Can't find ExternError. This usually means that this type was incompatible or not found.
WARN: Can't find ExternError. This usually means that this type was incompatible or not found.
WARN: Can't find ExternError. This usually means that this type was incompatible or not found.
```

Although the interface code is output in the generated C header file, the typedef like RustBuffer and ExternError type are not generated.

How to fix this problem?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1935)

**Comment by rfk** [comment]
Hi @chenzww, thanks for trying out the tool!

>  Then execute "cbindgen --lang c --crate <crate_name> --output <c_header_name>.h".

For uniffi, we do not use `cbindgen` but instead a separate tool named [`uniffi-bindgen`](https://crates.io/crates/uniffi_bindgen), which you should be able to install via `cargo install uniffi_bindgen`.  The guide has some brief instructions on using this tool [here](https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html).

What language are you trying to generate bindings for? I don't think it should be necessary to generate a separate C header for the scaffolding code, unless you're working on actually calling it from C code, which would be an interesting new use-case.

> Although the interface code is output in the generated C header file, the typedef like RustBuffer and ExternError
> type are not generated.

You might be able to generate declarations for these helpers by running `cbindgen` on the [`uniffi` crate](https://github.com/mozilla/uniffi-rs/tree/main/uniffi/src/ffi) itself, rather than on the code for your crate. But whether that's something you actually *need* to do, depends on what your final goal is. Can you say more about what you're looking to achieve with uniffi?

**Comment by chenzww** [comment]
> What language are you trying to generate bindings for?
I am looking for a way to generate binding dart use uniffi.

**Comment by rfk** [comment]
> I am looking for a way to generate binding dart use uniffi.

Sounds like fun!

Taking a look at how the [swift bindings generator](https://github.com/mozilla/uniffi-rs/tree/main/uniffi_bindgen/src/bindings/swift) currently work could be a good way to get started here.

If we start with one of the example crates, we can see what gets generated by the swift bindings backend:

```
> cd ./examples/sprites/
> ls ./src 
lib.rs          sprites.udl
>
> uniffi-bindgen generate -l swift ./src/sprites.udl
> ls ./src                                          
lib.rs                                  sprites.swift                           sprites.udl                             uniffi_sprites-Bridging-Header.h
```

For swift, uniffi generates two files: a `.h` file for C declarations of the functions exported by the Rust code, and a `.swift` file that imports those declarations and wraps then into a higher-level swift API.

The `uniffi_sprites-Bridging-Header.h` file is similar to what would be generated by `cbindgen`, but uniffi generats it directly based on [this template](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/Template-Bridging-Header.h).  (I do wonder whether we should use `cbindgen` for this, rather than generating our own header file using a custom template. The current setup was simply the easiest approach to get started with).

You might be able to use this header file as a starting point for importing those functions into Dart.

**Comment by chenzww** [comment]
Another topic. When I tried to look the examples output, all examples failed. I think it should be a simple way, so that examples can easily look the effect of foreign language execution.

**Comment by rfk** [comment]
> When I tried to look the examples output, all examples failed. 

Could you please post the commands you tried and the errors you got, if any? I agree that the examples should be a good place to go for that sort of thing, we might be able to tweak them to get them working for you.

**Comment by chenzww** [comment]
> > When I tried to look the examples output, all examples failed.
> 
> Could you please post the commands you tried and the errors you got, if any? I agree that the examples should be a good place to go for that sort of thing, we might be able to tweak them to get them working for you.

Post commands is not only limited effect, but also cumbersome. The best way to make the code execute well is use it without thinking command usage. Perhaps, it is worth consider use cargo-make workflow.

**Comment by rfk** [comment]
Thanks again for trying out the tool. I'm going to close out this issue as I don't think there's anything specifically actionable here.

I agree it should be easier to run the examples in an "exploratory" fashion, e.g. by going into `./examples/arithmetic` and running `cargo run` and having it give you useful guidance on getting dependencies installed and having the thing work correctly. Unfortunately I don't think we're in a position to prioritize the work of making that any more concrete at this time.
