### ISSUE TITLE
publish v0.7.0

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#376]
I tried to publish v0.7.0 to crates.io so that the new threadsafe annotation could be used by nimbus (and assumed that was significant enough warrant a new minor number!) - I even pushed the new branch to the repo, but running `cargo publish` resulted in:

> error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.

It looks like we need to update the owners :) I suspect this means we are going to need to wait for Ryan to get back.

cc @jhugman @travis79 for awareness.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2017)

**Comment by dmose** [comment]
Perhaps @linacambridge or @eoger might have a minute to update this on crates.io?

**Comment by dmose** [comment]
In particular, it'd be great if one of you could add @mhammond, @jhugman, and @dmose as owners.

**Comment by linacambridge** [comment]
Hey folks! 👋🏻 Oh wow, I didn't realize I'm still an owner! Please feel free to remove me if you like; one of y'all should be able to once you accept the creates.io invites. I don't think I need that level of access to your critical infra! 😅

**Comment by dmose** [comment]
@linacambridge we're almost there; thanks so much!  Can you also add me to uniffi_macros?

Thanks!

**Comment by rfk** [comment]
Thanks @linacambridge!

@dmose I've gone ahead and added you to `uniffi_macros` and will do a bit of editing to broaden the set of owners. I recall reading about some way to use teams as owners rather than individuals but it didn't work when I tried it last time (for reasons that I can no longer recall). We could have another go at it though.

**Comment by rfk** [comment]
> I recall reading about some way to use teams as owners 

Yep, wasn't able to make this work for what I assume are org-permission-related reasons.

@mhammond I've invited you to be an owner on the uniffi packages. @jhugman I tried to invite you but wasn't able to, I wonder if you need to first sign in to https://crates.io so that it knows about you as a user.

**Comment by rfk** [comment]
Finally, I have removed @linacambridge and @eoger as owners 😢.

**Comment by rfk** [comment]
(Note that I am deliberately not doing the actual publish of this new version, so we can roadtest the new permissions with someone else at the wheel)

**Comment by dmose** [comment]
I've published everything to crates.io, as per the release instructions at the bottom of the README.md.  However, the last step there says:

> Push your branch, and make a PR to request it be merged to the main branch.

```
    git push origin
```

It pushed just fine, but says that there's nothing to merge when I attempt to create a pull request.  I'm guessing that perhaps amending a commit message isn't enough for github to recognize that the commits are different?

**Comment by dmose** [comment]
No, I see what happened now.  I've been using `gh`, the official GitHub CLI interface to clone repos, and due to its convention, origin points to my fork, whereas upstream points to the mozilla fork.  So I've re-pushed to the mozilla fork, and have now created #377 for merging the version updates back to `main`.

**Comment by jhugman** [comment]
I've now signed into crates.io with Github OAuth.

**Comment by dmose** [comment]
Hmm, I'm no longer sure how my remotes got weirdly named, so I can no longer blame `gh`.  Anyway, no big deal.

I've sent invites to @jhugman

**Comment by dmose** [comment]
Keeping this open until the merge back to main completes.

**Comment by dmose** [comment]
Merged completed.
