### ISSUE TITLE
Implement required(?) [Blocking] || [Non-Blocking] annotations for some or all methods

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#378]
As an SDK user, I should have explicit guidance about the blocking/non-blocking semantics documented about (some? all?) interface methods, so that I don't inadvertently end up blocking on a thread where that's not allowed.

As an SDK developer, I should have to mark methods (especially, but mabe not exclusively) in ThreadSafe interfaces as either [Blocking] or [Non-Blocking], so that I am prompted to think specifically about these semantics as I am implementing and document them.

The exact definitions of these semantics need to be experimented with and/or nailed down.  See https://github.com/mozilla/uniffi-rs/pull/368#discussion_r557689320 and following for lots more context.

CC @rfk @mhammond @jhugman @travis79 @andreio

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2026)

**Comment by rfk** [comment]
See also [this earlier comment from @mhammond](https://github.com/mozilla/uniffi-rs/pull/368#issuecomment-760657371) about how uniffi might be able to help manage the locking for `[Blocking]` method calls.

**Comment by jhugman** [comment]
I'm deferring comment until the semantics of `Blocking` or `NonBlocking` means.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

We should do this ahead of the iOS integration and have a conversation with iOS engineers and Fenix to determine the correct assumptions for the ticket.

**Comment by dmose** [comment]
One way that we brainstormed to think about these was the idea of the annotations expressing things that the (consuming?) teams care about (is this blocking?  does it use the network? etc), and way ensuring that the SDK supports those constraints in an ongoing fashion.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

We discussed this a little in a recent team meeting, but we couldn't come up with anything that concretely seemed worth trying. Since the annotation would not have any effect on the generated doc, they basically serve as documentation. But how are they better than having actual documentation that says "this might block"? The only advantage would be that the tooling could force you to add one, but that doesn't necessarily force the consumer to read it.

I don't think this is worthwhile until it would have some visible effect on the generated code. For example, you could image that every function in the Kotlin bindings would be marked as `suspend` by default, forcing the caller to call them via a coroutine, unless we explicitly marked them as "non-blocking" in the interface definition.

The outcome from the meeting was basically: given how much broader discussion we're having right now about the next iteration of interface definition, we should close this and let it come back up organically as part of those discussions.
