### ISSUE TITLE
Kotlin errors being `FooErrorException` is awkward. 

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#442]
eg, [`ArithmeticErrorException` here](https://github.com/mozilla/uniffi-rs/blob/9aee2083ae51fd8e3e87682a2c10370aa2213617/examples/arithmetic/tests/bindings/test_arithmetic.kts#L9) - all other bindings have the more natural `ArithmeticError` as defined in the udl.

It's grating on me in https://github.com/mozilla/application-services/pull/4068 so thought I'd ask if this really is idiomatic?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2208)

**Comment by rfk** [comment]
I agree this is pretty yuck :-/

Naively, it feels like the right thing to do would be to have the exception class named `ArithmeticError` just like in other bindings. If calling it "FooException" is really important for idiomatic Kotlin reasons, we could also consider translating error classes named `FooError` into `FooException` automatically in the bindings.

@grigoryk maybe you can give us a bit of a gut-check here from the PoV of a consumer? Looking at the FxA error class wrappers [here](https://github.com/mozilla-mobile/android-components/blob/bfaf514793dd20f9f12d3f551f9ff3e470f52727/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt#L10), would it be appropriate for us to rename `fxaclient.FxaErrorException` to just `fxaclient.FxaError`?

**Comment by npars** [comment]
In java a "FooError" would typically be expected to extend [Error](https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html) and would be considered fatal. Meanwhile "FooException" would be expected to extend [Exception](https://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html) and be non-fatal / catchable. I assume that was the original intention behind tacking on "Exception" at the end.

**Comment by jhugman** [comment]
@npars is correct: from a JVM point of view, Error means something very specific. Removing an `Error` suffix before appending `Exception` may be the write thing to do here, even if low priority.

Stymergic hint: the quickest dirtiest path I can think of would be doing this in `class_name_kt` in `gen_kotlin.rs`.

**Comment by grigoryk** [comment]
ditto JVM Error meaning.

I agree with @jhugman's suggestion RE dropping `Error` before the name conversion, so we end up w/ `ArithmeticException`, not `ArithmeticErrorException`.

**Comment by rfk** [comment]
I support the direction we're going here, and it seems inline with other name-munging that we do in order to make the generated bindings more idiomtic. To sum up, I believe the consensus desired behavior to be:

* Continue to encourage `[Error]` declarations to be named like `FooError` in the interface definition.
* When [generating the Kotlin bindings for an `Error`](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt), change `FooError` into `FooException` in the public API.

I think this will actually be a pretty self-contained change. The mechanics of our Kotlin error handling are already split into two pieces for any given `FooError`:

* A [`FooError` class](https://github.com/mozilla/uniffi-rs/blob/db7e0ca81c36ac7a8f2d931215dd06607723b7d8/uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt#L101) that derives from a base `RustError`, defining the C FFI struct that gets used when calling over the FFI; this is a JNA `Structure.ByReference` and is not throwable.
* A wrapping [`FooErrorException` class](https://github.com/mozilla/uniffi-rs/blob/db7e0ca81c36ac7a8f2d931215dd06607723b7d8/uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt#L121) that extends `Exception` and is the thing that is actually exposed in the public API.
    * This in turn [defines an inner subclass per error variant](https://github.com/mozilla/uniffi-rs/blob/db7e0ca81c36ac7a8f2d931215dd06607723b7d8/uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt#L123), e.g. variant `FooError::BadThing` in the udl shows up in the Kotlin API as the class `FooErrorException.BadThingException`.

So concretely, I think we can have the change we want here by adjusting only the name-generating logic in the [exception wrapper class](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt#L121-L125):

* Make a new [Kotlin template filter](https://github.com/mozilla/uniffi-rs/blob/db7e0ca81c36ac7a8f2d931215dd06607723b7d8/uniffi_bindgen/src/bindings/kotlin/gen_kotlin.rs#L70) like `exception_name_kt` that removes any `"Error"` suffix from a name and then appends `"Exception"`.
* Use the filter when [generating names](https://github.com/mozilla/uniffi-rs/blob/db7e0ca81c36ac7a8f2d931215dd06607723b7d8/uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt#L121) for both the Exception wrapper class and its inner classes.

I do want to flag though, that this will potentially interact with the work proposed in #460. In fact, it could be a really nice way for someone like @bendk to ease in to the logic for handling errors before taking on that bigger piece of work 😁

**Comment by sebastient** [comment]
It would be helpful for the documentation on defining error types in UDL clarifies that errors cannot be named `Error` which is typical in Rust but fails because this munges the name to Exception, which it cannot be.

**Comment by mhammond** [comment]
Kotlin renaming `Error` to `Exception` is expected and should not cause problems. Can you please open a new issue describing your problem in more detail?
