### ISSUE TITLE
Support rich structured Enums for reporting errors

### ISSUE THREAD

**Issue by skhamis** [mozilla/uniffi-rs#460]
## Problem 
Currently Uniffi does not allow too much flexibility in terms of having nested enums which makes things a bit tricky when trying to create richer structured error classes.

In the current effort to [uniffi logins component in application-services](https://github.com/mozilla/application-services/pull/4068) we've run into a bit of limitations in porting over some of the errors.

## Proposed solution
Having a structure similar to dictionaries/interfaces in the `.udl` file might allow the generation of these errors to be more robust. Instead of:
```
[Error]
enum LoginsStorageError {
    "UnexpectedLoginsStorageError",
    "SyncAuthInvalid",
    "MismatchedLock",
    "NoSuchRecord",
    "IdCollision",
    "InvalidRecord",
    "InvalidKey",
    "RequestFailed",
    "Interrupted",
};
```

We could do something like
```
[Error]
enum LoginsStorageError {
   String UnexpectedLoginsStorageError,
   InvalidReason InvalidRecord,
   ...
};

enum InvalidReason {
  "EmptyPassword",
  "EmptyOrigin",
   ...
}

```

This will allow having enum (or other) types be expected and consequently allow for richer errors to be passed over.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-60)
┆Epic: UniFFI
┆Issue Number: UNIFFI-60
┆Sprint End Date: 2021-08-06

**Comment by rfk** [comment]
I really like the gist of this proposal, and see a lot of value in being able to pass richer structured error information. We're probably going to have to fiddle around to find a good syntax that fits within the constraints of our current IDL. Perhaps along the lines of the current rich enum syntax, which is:

```
[Enum]
interface {
  Variant(Type field, ...);
  ....
}
```

Allowing `Error` to use the same structure might work well for our needs here:

```
[Error]
interface {
  Variant(Type field, ...);
  ...
}
```

I think maintaining the symmetry of errors being a special kind of enum makes sense.

For context for @skhamis and others: UniFFI currently (ab)uses an off-the-shelf WebIDL parser, which really helped us get up and running quickly, but means we're syntactically limited to what's supported by WebIDL. There's some discussion of lightly hacking our way around this limitation for enums in https://github.com/mozilla/uniffi-rs/pull/381.

**Comment by skhamis** [comment]
Looking more at the syntax you've laid out, I think that is already a better way to go! It's easy to read and still gives the flexibility. On the named fields, that doesn't seem to be a blocker given the pros for this paradigm.

**Comment by rfk** [comment]
I've been thinking a bit about how to make this actionable. There are a lot of moving parts, but it'll be a worthwhile effort.

The way we handle errors is currently very special-cased, and it's based on the [`ExternError`](https://github.com/mozilla/ffi-support/blob/main/src/error.rs) struct from `ffi-support`. This struct plays nicely with the other helpers from `ffi-support`, but is specifically limited to containing only an integer error `code` and a string `message`. If we want richer structured errors, we'll need to extend or replace this class with something of our own (similar to how we use our own `RustBuffer` struct rather than the one from `ffi-support`).

Error handling is also special-cased in codegen, as it's the only place where our function signatures take a mutable "out" param. See e.g. the [special error param in the Rust scaffolding](https://github.com/mozilla/uniffi-rs/blob/041660d62b16b22a130361347432fc9612a26a51/uniffi_bindgen/src/templates/macros.rs#L31) and the [`ByReference` error struct in the Kotlin bindings](https://github.com/mozilla/uniffi-rs/blob/041660d62b16b22a130361347432fc9612a26a51/uniffi_bindgen/src/bindings/kotlin/templates/macros.kt#L73), each of which is defined to match the shape of `ExternError`. The idea is that we wind up with an FFI function signature like:

```
ResultType my_example_function(ArgType1 arg1, ..., ArgTypeN argN, *ExternError err);
```

If the underlying Rust call succeeds, we directly return the result; if it fails when we return a default value for the result and populate the pointed-to `err` with error information.

What might it look like to lean in to "errors are a special kind of enum" in order to implement this feature request?

When parsing the interface definition, we could make the [`Error` type](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/interface/error.rs) actually parse and store an underlying [`Enum`](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/interface/enum_.rs) rather than its current behaviour of just [storing a list of variant names](https://github.com/mozilla/uniffi-rs/blob/041660d62b16b22a130361347432fc9612a26a51/uniffi_bindgen/src/interface/error.rs#L53). This would let us leverage the existing syntax for rich enum types without re-inventing any of it. It might make sense to also automatically add an `InternalError` variant to each error enum, to explicitly handle the case of reporting a panic.

Next, recall that enums are currently always passed across the FFI by serializing them into a `RustBuffer`. This means that we could replace our use of the `ffi_support::ExternError` struct with a direct use of `RustBuffer`, passing a pointer to a `RustBuffer` struct as the final argument to each fallible FFI function:

```
           change this ------------------------------------------------+
                                                                       V
ResultType my_example_function(ArgType1 arg1, ..., ArgTypeN argN, *RustBuffer err_buf);
```

If the underlying Rust call succeeds, it can return the result as before. If the underlying Rust call fails, it can capture the resulting Error, lower it into a buffer using the existing logic for Enums, and return the resulting buffer through the mutable `err_buf` out param just like we currently do for errors. On the foreign-language side, the calling code can check whether `err_buf` has non-zero length and if so, lift an Enum instance from the buffer and throw it as an error.

One minor hiccup would be that we could no longer use [`ffi_support::call_with_result`](https://github.com/mozilla/ffi-support/blob/028cc62bedf97a5002b5d1f523cb323c39ed5b73/src/lib.rs#L186) because that depends on `ExternError` for error reporting. We may have to take a copy of it and tweak it for our needs; luckily it's a pretty small function. (It's very important and does a lot of well-thought-out things, it's just lines-of-code pretty small).

One final thought: we could also consider moving the `err_buf` parameter to be the *first* argument rather than the last. Having it as the final argument makes more sense for human-written function signatures, but I have a theory that codegen would be simpler if it were always present and always as the first argument. Just something to think about while we're in there :-)

Overall, I think this could actually result in a net simplification and reduction in code, because we can re-use a lot of the existing enum-handling logic rather than implementing separate special cases for errors.

**Comment by rfk** [comment]
>  I have a theory that codegen would be simpler if it were always present and always as the first argument.

Specifically:

* If you're always making it the first argument, you can unconditionally render it directly with no decoration, rather than having to figure out whether or not to include a leading `,` to separate it from other args.
* When rendering the rest of the argument list, if you know that there was always at least one existing argument already rendered, you can unconditionally render each new argument with a leading `,` and the list will come out correctly.

**Comment by bendk** [comment]
Could we leverage the enum/RustBuffer code even further?  I'm wondering if the scaffolding could generate something like this: 

```
void my_example_function(*RustBuffer result_buf, ArgType1 arg1, ..., ArgTypeN argN);
```

`result_buf` would be filled with an enum with these variants:
  - `Success(R)`
  - `Err(E)`
  - `PanicError(std:Error)`

This way:
  - The result is always in 1 place, which seems nice
  - There's a simple way to return errors from panics.  With the previous one, I wasn't sure how to handle that without forcing the underlying rust error to have a `from std::Error` implementation which didn't seem right.

**Comment by rfk** [comment]
> I just realized that this probably isn't going to work for all return values. 

Right, my hesitation would be that not everything gets serialized to a buffer to be returned (and probably we want to try to serialize *fewer* things over time, for performance).

> But maybe it still makes sense to create an Enum that can hold either the normal error or the panic error.

This could work out nicely. I'm interpreting what you're saying here as something like this definition inside UniFFI:

```
pub enum FFICallError<E> {
  Err(E), // a "clean" error of the specified type
  Panic(String), // a panic, which we caught and are returning over the FFI
}
```

And you could provide a default `ViaFfi` implementation that delegates out to the one for the user-provided type `E`. Sounds worth exploring!

> without forcing the underlying rust error to have a from std::Error implementation which didn't seem right

We could auto-generate such a thing if we wanted to, but probably it would still depend on the rust error having a special "internal error" variant, which I agree does seem annoying for the consumer.

**Comment by bendk** [comment]
>  But maybe it still makes sense to create an Enum that can hold either the normal error or the panic error.

I almost have this working, but I think there's a fatal flaw.  If there's a panic, then we would need to do some allocations to write out `FFICallError::Panic` to the `Vec<u8>` and create a `RustBuffer` out of that.  If those allocations fail then we're in really bad territory.  Too bad, but I think we can do something fairly similar without using `RustBuffer` for the panic.

**Comment by rfk** [comment]
Another option could be to report panics separately from deliberate errors, e.g. adding a second out param that is just for "did this panic?".

**Comment by bendk** [comment]
That's pretty much what I'm doing.  The second param is going to have 3 possible values: success/error/panic.  The goal is to only create the `RustBuffer` in the error case.
